#!/bin/bash

if [ -z "$RIFT_INSTALL" ]; then
   rift_install="/"
else
   rift_install=$RIFT_INSTALL
fi

zsh_bin="${rift_install}/usr/bin/zsh"
zsh_cmd=${zsh_bin}

while [[ $# > 0 ]]
do
  arg=$1
  case $arg in
    --trace_level| --schema_listing | --netconf_host | --netconf_port | --username | --passwd | --vm_instance)
      zsh_cmd="${zsh_cmd} $1 $2"
      shift 2
    ;;
    --netconf)
      if [ -n "${rwmsg}" ]; then
         echo "Netconf mode and rwmsg mode cannot be specified together"
         exit 1
      fi
      netconf=1
      shift
    ;;
    --rwmsg)
      if [ -n "${netconf}" ]; then
         echo "Netconf mode and rwmsg mode cannot be specified together"
         exit 1
      fi
      rwmsg=1
      zsh_cmd="${zsh_cmd} --rwmsg"
      shift
    ;;
    --help)
      show_help=1
      shift
    ;;
    *)
     echo "Error Unknown option $arg to rwcli"
     exit 1
  esac
done

if [ -n "${show_help}" ]; then
   zsh_cmd="${zsh_bin} --help"
   exec ${zsh_cmd}
fi

schema_dir="${rift_install}/var/rift/schema"
file_proto_yutil="${rift_install}/usr/bin/rwyangutil"

# Check if the dynamic schema directory exists, if not create it
if [ ! -d ${schema_dir} ]; then
   echo "Creating ${schema_dir} directory.."
   ${file_proto_yutil} --create-schema-dir
   estat=$?
   if [[ $estat != 0 ]]; then
      echo "Failed to create ${schema_dir} directory"
      exit 1
   fi
fi

echo ${zsh_cmd}
exec ${zsh_cmd}
