
/*
 * 
 * (c) Copyright RIFT.io, 2013-2016, All Rights Reserved
 *
 */


/*
 * @file rwnetconf_client-c.in.h
 * @author Tom Seidenberg
 * @date 2014/05/21
 * @brief RW.Netconf client library C plugin.
 */

#ifndef RWNETCONF_CLIENT_PLUGIN_C_H__
#define RWNETCONF_CLIENT_PLUGIN_C_H__

#include "rwnetconf.h"

#define VAPI_TO_C_AUTOGEN
#ifdef VAPI_TO_C_AUTOGEN

/* Don't modify the code below, it is autogenerated */

G_BEGIN_DECLS

G_MODULE_EXPORT void peas_register_types(PeasObjectModule *module);

#define RWNETCONF_CLIENT_PLUGIN_C_EXTENSION_TYPE (rwnetconf_client_c_extension_get_type())

typedef struct _NetconfClientPluginCExtension      NetconfClientPluginCExtension;
typedef struct _NetconfClientPluginCExtensionClass NetconfClientPluginCExtensionClass;

struct _NetconfClientPluginCExtension {
  PeasExtensionBase parent_instance;
};

struct _NetconfClientPluginCExtensionClass {
  PeasExtensionBaseClass parent_class;
};

GType rwnetconf_client_c_extension_get_type (void) G_GNUC_CONST;

//
//NetconfClientPlugin.Api
//
#define RWNETCONF_CLIENT_PLUGIN_API_C_EXTENSION_TYPE (rwnetconf_client_api_c_extension_get_type())

typedef struct _NetconfClientPluginApiCExtension      NetconfClientPluginApiCExtension;
typedef struct _NetconfClientPluginApiCExtensionClass NetconfClientPluginApiCExtensionClass;

struct _NetconfClientPluginApiCExtension {
  PeasExtensionBase parent_instance;
};

struct _NetconfClientPluginApiCExtensionClass {
  PeasExtensionBaseClass parent_class;
};

GType rwnetconf_client_api_c_extension_get_type (void) G_GNUC_CONST;

G_END_DECLS

#endif //VAPI_TO_C_AUTOGEN

#endif // RWNETCONF_CLIENT_PLUGIN_C_H__
