#!/bin/bash

# this script needs to be run on a controller node after every reboot
if [ -f /root/keystonerc_admin ]; then
    . /root/keystonerc_admin
    pub_subnet_name="public_subnet"
elif [ -f /home/stack/devstack/accrc/admin/admin ]; then
    . /home/stack/devstack/accrc/admin/admin
    pub_subnet_name="public-subnet"
else
   echo "Can't find /root/keystonerc_admin or /home/stack/devstack/accrc/admin/admin"
   exit 1
fi

public_subnet_cidr=`neutron net-list | awk '/public/{print $7}' | cut -d '/' -f2`
routerip=`neutron router-show router1 | perl -n -e 'print $1 if /(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})/;'`

if [ -z "$routerip" ]; then
    echo error parsing routers IP
    neutron router-port-list router1
    exit 1
fi
    
private_subnet=`neutron net-list | awk '/ private / { print $7; }'`
if [ -z "$private_subnet" ]; then
    echo error retrieving private subnet
    exit 1
fi
myip=`neutron subnet-show $pub_subnet_name | awk '/gateway_ip/ { print $4; }'`
if [ -z "$myip" ]; then
    echo error retrieving my ip address
    exit 1
fi

set -x
sudo ip addr add ${myip}/${public_subnet_cidr} dev br-ex
sudo route add -net $private_subnet gw $routerip

if [ -f /root/keystonerc_admin ]; then
    systemctl restart neutron-l3-agent.service
    systemctl restart neutron-server 
fi

exit 0

